name: Dummy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
    - name: ls
      run: ls
    - name: pwd
      run: pwd
    - name: env
      run: env
    - name: os info
      run: cat /etc/*release
      

